#!/bin/bash

# Create simple PNG icons using base64 encoded data
# These are minimal red square icons that will work for the extension

# 16x16 red icon (base64 encoded PNG)
echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMklEQVR42mP8z8DwHwyZGKgAjIyMDP8ZGBj+M1ABRkZGhv8MDEwMVACmpqb/DAwMDAAAtpwH/VT0+l8AAAAASUVORK5CYII=" | base64 -d > icon16.png

# 48x48 red icon
echo "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAARUlEQVR42u3OMQ0AAAgDse9fNEAmsgDmm4KMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjC8VWAMfFcSc9vAAAAAElFTkSuQmCC" | base64 -d > icon48.png

# 128x128 red icon
echo "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAnElEQVR42u3QMQ0AAAgEoP+fNhhDJrBAklZ1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4FsGtgAHFd0XRq4AAAAASUVORK5CYII=" | base64 -d > icon128.png

echo "Icons created successfully!"
ls -lh icon*.png
